# Generated by Django 3.1.7 on 2021-04-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210411_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_shop',
            old_name='comment',
            new_name='comment_shop',
        ),
        migrations.RenameField(
            model_name='review_shop',
            old_name='rating',
            new_name='rating_shop',
        ),
    ]
