# Generated by Django 3.1.7 on 2021-04-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210411_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_shop',
            old_name='comment_shop',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review_shop',
            old_name='rating_shop',
            new_name='rating',
        ),
    ]
