# Generated by Django 3.1.7 on 2021-04-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210411_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
